<a href="https://colab.research.google.com/github/computer0796579/Angular/blob/main/Getting_started_with_BigQuery.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Before you begin


1.   Use the [Cloud Resource Manager](https://console.cloud.google.com/cloud-resource-manager) to Create a Cloud Platform project if you do not already have one.
2.   [Enable billing](https://support.google.com/cloud/answer/6293499#enable-billing) for the project.
3.   [Enable BigQuery](https://console.cloud.google.com/flows/enableapi?apiid=bigquery) APIs for the project.

### Provide your credentials to the runtime

In [1]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

### Declare the Cloud project ID which will be used throughout this notebook

In [2]:
project_id = 'api-project-241561302097'

### Optional: Enable data table display

Colab includes the ``google.colab.data_table`` package that can be used to display large pandas dataframes as an interactive data table.
It can be enabled with:

In [3]:
%load_ext google.colab.data_table

If you would prefer to return to the classic Pandas dataframe display, you can disable this by running:
```python
%unload_ext google.colab.data_table
```

# Use BigQuery via magics

The `google.cloud.bigquery` library also includes a magic command which runs a query and either displays the result or saves it to a variable as a `DataFrame`.

In [4]:
# Display query output immediately

%%bigquery --project {project_id}
SELECT
  COUNT(*) as total_rows
FROM `bigquery-public-data.samples.gsod`

Query is running:   0%|          |

Downloading:   0%|          |

   total_rows
0   114420316

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_0.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

In [5]:
# Save output in a variable `df`

%%bigquery df --project {project_id}
SELECT
  COUNT(*) as total_rows
FROM `bigquery-public-data.samples.gsod`

Query is running:   0%|          |

Downloading:   0%|          |

In [6]:
df

   total_rows
0   114420316

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['index']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'index'}, axis=1)
              .sort_values('index', ascending=True))
  xs = counted['index']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_1.sort_values('index', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('index')
_ = plt.ylabel('count()')

# Use BigQuery through BigQuery DataFrames

See [BigQuery documentation](https://cloud.google.com/bigquery/docs) and [BigQuery DataFrames reference documentation](https://cloud.google.com/python/docs/reference/bigframes/latest).

The [GSOD sample table](https://console.cloud.google.com/bigquery?p=bigquery-public-data&d=samples&t=gsod&page=table) contains weather information collected by NOAA, such as precipitation amounts and wind speeds from late 1929 to early 2010.

### Sample approximately 2000 random rows

In [7]:
import bigframes.pandas as bpd

bpd.options.bigquery.project = project_id

sample_count = 2000

df = bpd.read_gbq("bigquery-public-data.samples.gsod")

row_count = df.shape[0]

df = df.sample(sample_count)

print('Full dataset has %d rows' % row_count)

Full dataset has 114420316 rows

### Describe the sampled data

In [ ]:
df.describe()

,station_number,wban_number,year,month,day,mean_temp,num_mean_temp_samples,mean_dew_point,num_mean_dew_point_samples,mean_sealevel_pressure,...,mean_visibility,num_mean_visibility_samples,mean_wind_speed,num_mean_wind_speed_samples,max_sustained_wind_speed,max_gust_wind_speed,max_temperature,min_temperature,total_precipitation,snow_depth
count,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,2000.0,1905.0,1905.0,1503.0,...,1784.0,1784.0,1977.0,1977.0,1944.0,272.0,2000.0,0.0,1819.0,103.0
mean,509229.928,91090.3395,1987.1865,6.5395,16.016,52.792,12.9165,42.083045,12.740682,1014.776314,...,12.512332,12.556614,6.718816,12.843703,12.149588,25.480882,44.03815,<NA>,0.08061,10.0
std,301968.506371,25341.066819,16.104204,3.424953,8.722717,23.463624,7.867431,22.223635,7.84855,9.095351,...,9.736078,7.797144,4.952929,7.847506,7.031532,9.874374,23.735059,<NA>,0.288874,11.402837
min,10070.0,3103.0,1936.0,1.0,1.0,-52.900002,4.0,-57.299999,4.0,959.5,...,0.0,4.0,0.0,4.0,1.0,8.0,-61.799999,<NA>,0.0,0.4
25%,236910.0,99999.0,1977.0,4.0,9.0,39.599998,7.0,29.700001,7.0,1009.400024,...,6.5,6.0,3.3,7.0,7.8,19.0,32.0,<NA>,0.0,2.4
50%,542920.0,99999.0,1989.0,6.0,16.0,55.0,8.0,43.5,8.0,1014.5,...,9.9,8.0,5.8,8.0,11.1,23.299999,46.400002,<NA>,0.0,5.9
75%,725090.0,99999.0,2001.0,10.0,23.0,70.0,23.0,57.5,23.0,1020.099976,...,15.0,23.0,8.9,23.0,15.5,29.9,60.799999,<NA>,0.01,15.0
max,999999.0,99999.0,2010.0,12.0,31.0,101.400002,24.0,81.800003,24.0,1055.699951,...,99.400002,24.0,53.5,24.0,88.0,89.0,91.0,<NA>,3.54,82.699997

### View arbitrary 10 rows

In [ ]:
df.peek(10)

Warning: Total number of columns (31) exceeds max_columns (20). Falling back to pandas display.

,station_number,wban_number,year,month,day,mean_temp,num_mean_temp_samples,mean_dew_point,num_mean_dew_point_samples,mean_sealevel_pressure,...,min_temperature,min_temperature_explicit,total_precipitation,snow_depth,fog,rain,snow,hail,thunder,tornado
35349954,638870,99999,1961,6,8,68.599998,5,47.0,5,<NA>,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False
2497913,543370,99999,1982,3,27,38.400002,8,28.799999,8,1026.099976,...,<NA>,<NA>,0.04,<NA>,False,False,False,False,False,False
46805715,38660,99999,1989,9,14,58.799999,22,54.0,22,<NA>,...,<NA>,<NA>,<NA>,<NA>,False,False,False,False,False,False
45388121,713970,99999,1984,7,31,69.300003,24,57.099998,24,1017.900024,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False
105768579,287040,99999,1969,11,1,32.0,8,29.4,8,1002.700012,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False
49492447,10250,99999,1996,8,18,51.200001,24,47.400002,24,1010.900024,...,<NA>,<NA>,0.12,<NA>,False,False,False,False,False,False
45658252,161150,99999,1994,7,14,75.800003,13,70.400002,13,<NA>,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False
99477822,281310,99999,1981,11,8,30.200001,7,25.1,6,1020.5,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False
77950004,722926,3154,1996,12,8,57.5,24,44.200001,21,1019.200012,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False
99829908,107710,99999,2002,7,28,69.699997,16,55.200001,16,1020.700012,...,<NA>,<NA>,0.0,<NA>,False,False,False,False,False,False

### View 10 highest total_precipitation samples

In [ ]:
df.sort_values('total_precipitation', ascending=False).head(10)[['station_number', 'year', 'month', 'day', 'total_precipitation']]

           station_number  year  month  day  total_precipitation
48210163           722140  1976     11   28                 3.54
100473809          322460  1961      3   26                 2.95
96170642           972600  1979      3    1                 2.76
61880958           476550  1961      4   26                 2.72
43527842           619740  1983     10   16                  2.6
34344262           964210  1996      4   29                 2.56
43236540           483280  1986      5   23                 2.52
114338091          851230  2005      3   19                 2.44
104373932           82150  1989     11   20                 2.36
35250392           471065  1975      7   24                 2.36

[10 rows x 5 columns]

# Use BigQuery through google-cloud-bigquery

See [BigQuery documentation](https://cloud.google.com/bigquery/docs) and [library reference documentation](https://googlecloudplatform.github.io/google-cloud-python/latest/bigquery/usage.html).

The [GSOD sample table](https://console.cloud.google.com/bigquery?p=bigquery-public-data&d=samples&t=gsod&page=table) contains weather information collected by NOAA, such as precipitation amounts and wind speeds from late 1929 to early 2010.

### Sample approximately 2000 random rows

In [ ]:
from google.cloud import bigquery

client = bigquery.Client(project=project_id)

sample_count = 2000
row_count = client.query('''
  SELECT
    COUNT(*) as total
  FROM `bigquery-public-data.samples.gsod`''').to_dataframe().total[0]

df = client.query('''
  SELECT
    *
  FROM
    `bigquery-public-data.samples.gsod`
  WHERE RAND() < %d/%d
''' % (sample_count, row_count)).to_dataframe()

print('Full dataset has %d rows' % row_count)

Full dataset has 114420316 rows

### Describe the sampled data

In [ ]:
df.describe()

Warning: Total number of columns (23) exceeds max_columns (20). Falling back to pandas display.

,station_number,wban_number,year,month,day,mean_temp,num_mean_temp_samples,mean_dew_point,num_mean_dew_point_samples,mean_sealevel_pressure,...,mean_visibility,num_mean_visibility_samples,mean_wind_speed,num_mean_wind_speed_samples,max_sustained_wind_speed,max_gust_wind_speed,max_temperature,min_temperature,total_precipitation,snow_depth
count,1917.0,1917.0,1917.0,1917.0,1917.0,1917.000000,1917.0,1837.000000,1837.0,1428.000000,...,1723.000000,1723.0,1894.000000,1894.0,1858.000000,258.000000,1915.000000,0.0,1745.000000,108.000000
mean,502447.478352,89822.252478,1986.604591,6.489828,15.766823,51.783516,13.098592,41.707730,13.045727,1014.851050,...,11.872838,12.859547,6.969799,13.047518,12.337675,24.364341,43.315718,NaN,0.068115,9.568518
std,299118.262175,27008.869915,16.451458,3.453014,8.841116,24.125164,7.974397,22.294639,7.981465,9.420865,...,9.545982,7.936962,4.987575,7.953833,6.642102,9.405444,24.079599,NaN,0.264338,8.773491
min,10015.0,6.0,1932.0,1.0,1.0,-88.599998,4.0,-64.500000,4.0,966.000000,...,0.000000,4.0,0.000000,4.0,1.000000,5.800000,-94.500000,NaN,0.000000,0.400000
25%,235270.0,99999.0,1977.0,3.0,8.0,37.000000,7.0,28.900000,7.0,1009.599976,...,6.300000,7.0,3.500000,7.0,7.800000,18.100000,30.200001,NaN,0.000000,2.000000
50%,532760.0,99999.0,1989.0,6.0,16.0,54.500000,8.0,44.099998,8.0,1014.599976,...,9.300000,8.0,6.000000,8.0,11.700000,22.900000,46.000000,NaN,0.000000,6.700000
75%,724555.0,99999.0,2000.0,10.0,24.0,70.199997,24.0,57.299999,23.0,1020.099976,...,14.600000,23.0,9.200000,23.0,15.500000,28.000000,60.299999,NaN,0.010000,13.400000
max,999999.0,99999.0,2010.0,12.0,31.0,98.500000,24.0,79.800003,24.0,1059.800049,...,99.400002,24.0,46.400002,24.0,68.000000,62.200001,91.599998,NaN,4.530000,34.599998

### View the first 10 rows

In [ ]:
df.head(10)

Warning: Total number of columns (31) exceeds max_columns (20). Falling back to pandas display.

,station_number,wban_number,year,month,day,mean_temp,num_mean_temp_samples,mean_dew_point,num_mean_dew_point_samples,mean_sealevel_pressure,...,min_temperature,min_temperature_explicit,total_precipitation,snow_depth,fog,rain,snow,hail,thunder,tornado
0,942030,99999,1948,2,15,81.000000,7,76.900002,7,NaN,...,NaN,<NA>,0.01,NaN,False,False,False,False,False,False
1,722580,13960,1953,8,14,86.800003,24,70.800003,24,1016.799988,...,NaN,<NA>,0.00,NaN,False,False,False,False,False,False
2,725430,94822,1975,5,12,55.400002,24,42.200001,24,1013.200012,...,NaN,<NA>,0.04,NaN,False,False,False,False,False,False
3,299150,99999,1979,8,31,71.900002,6,52.099998,6,1017.200012,...,NaN,<NA>,0.00,NaN,False,False,False,False,False,False
4,310040,99999,1986,12,27,-37.299999,6,-43.500000,6,1047.500000,...,NaN,<NA>,0.04,NaN,False,False,False,False,False,False
5,370470,99999,1987,10,14,50.099998,6,45.599998,6,1023.900024,...,NaN,<NA>,0.00,NaN,False,False,False,False,False,False
6,725127,4726,1989,1,6,25.299999,18,22.100000,18,NaN,...,NaN,<NA>,0.00,NaN,True,True,True,True,True,True
7,684380,99999,1994,7,1,38.599998,6,20.799999,6,NaN,...,NaN,<NA>,0.00,NaN,False,False,False,False,False,False
8,443020,99999,1994,12,11,0.100000,7,-3.100000,7,1033.599976,...,NaN,<NA>,0.00,1.6,False,False,False,False,False,False
9,110320,99999,1994,12,11,45.599998,8,43.799999,8,1026.000000,...,NaN,<NA>,0.35,NaN,False,False,False,False,False,False

In [ ]:
# 10 highest total_precipitation samples
df.sort_values('total_precipitation', ascending=False).head(10)[['station_number', 'year', 'month', 'day', 'total_precipitation']]

      station_number  year  month  day  total_precipitation
632           594930  1992      6   13                 4.53
1139          973720  2008      2    9                 3.78
193           209630  1987     10   18                 3.50
1445          232050  1969      3   31                 2.76
1235          216360  1973      9   27                 2.17
1755          478970  1999      6   19                 2.17
1831          986180  1996     10    8                 2.13
1018          321660  1984      9   10                 1.57
176           478070  1963      8   28                 1.57
725            73740  1988     10    3                 1.54

# Use BigQuery through pandas-gbq

The `pandas-gbq` library is a community led project by the pandas community. It covers basic functionality, such as writing a DataFrame to BigQuery and running a query, but as a third-party library it may not handle all BigQuery features or use cases.

[Pandas GBQ Documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_gbq.html)

In [ ]:
import pandas_gbq

df = pandas_gbq.read_gbq('''
  SELECT name, SUM(number) as count
  FROM `bigquery-public-data.usa_names.usa_1910_2013`
  WHERE state = 'TX'
  GROUP BY name
  ORDER BY count DESC
  LIMIT 100;
''', project_id=project_id, dialect='standard', progress_bar_type=None)

df.head()

      name   count
0    James  272793
1     John  235139
2  Michael  225320
3   Robert  220399
4    David  219028

# Syntax highlighting
`google.colab.syntax` can be used to add syntax highlighting to any Python string literals which are used in a query later.

In [ ]:
from google.colab import syntax

query = syntax.sql('''
SELECT
  COUNT(*) as total_rows
FROM
  `bigquery-public-data.samples.gsod`;
''')

pandas_gbq.read_gbq(
    query,
    project_id=project_id, dialect='standard', progress_bar_type=None)

   total_rows
0   114420316